name: Deploy Lambda

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create Lambda zip
        run: |
          zip -j function.zip lambda_function.py
      
      - name: Validate CloudFormation
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation.yml \
            --region us-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID2026 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY2026 }}
      
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name lambda-cicd-function \
            --zip-file fileb://function.zip \
            --region us-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID2026 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY2026 }}